"""
Vedic Engine — AI Interpretation Layer (OpenAI GPT)
====================================================
Optional module that wraps the mathematical engine output with
natural-language narratives generated by GPT-4o.

Requires: pip install openai
Requires: OPENAI_API_KEY environment variable (or pass api_key directly)
"""
from vedic_engine.ai.interpreter import VedicInterpreter

__all__ = ["VedicInterpreter"]
